### ISSUE TITLE
Incompatible with Ghost 2.0 (how to install)

### ISSUE THREAD

**Issue by matthewpennell** [nickisnoble/ghost-theme-unit-test#1]
Just leaving this here as a note to anyone else wondering whether it will work with the latest 2.0 version of Ghost. **The answer is no.**

The current version (2.1.3 as of this writing) will refuse to import the dummy JSON content - it recommends installing Ghost 1.0 before importing, and then upgrading to v2. You can do this as follows:

* Create your installation folder and `cd` into it.
* Run `ghost install --local --v-1` to install a pre-2.0 version.
* Visit `http://localhost:2368/ghost/` and create your account.
* Go to Settings > Labs. You can now use the 'Import Content' area to upload the JSON file. Note that this cause the actual site to start throwing 500 errors.
* From the command line run `ghost update` to update your local version to version 2.

You now have all of the unit test content in a 2.0 Ghost blog.

**Comment by matthewpennell** [comment]
Here is a JSON dump of the same unit test content taken from a fresh 2.0 install, which can be imported into a fresh 2.0 Ghost install:

[ghost-theme-unit-test-2.0.json.zip](https://github.com/nickisnoble/ghost-theme-unit-test/files/2407687/ghost-theme-unit-test-2.0.json.zip)

If @nickisnoble is still active, hopefully he can add this to the repo as the default set of test content. :)

**Comment by Nekaravaev** [comment]
@matthewpennell, 
Thanks a lot!

**Comment by Adondriel** [comment]
Can confirm that the file from @matthewpennell works on V3

**Comment by nickisnoble** [comment]
@matthewpennell Thank you so much!

I completely missed this whole thread, need to clean up my notification settings.

Happy to add this, or you can do a pull request so that you get credit 🎉

**Comment by matthewpennell** [comment]
No worries, I'm not even using Ghost any more so you go ahead. :)
